### PR TITLE
Front end update

### PR DESCRIPTION
**Pull request by willyyhuang**
Solved #67 #58 #57 
Changes made: 
SHC polish, add object icon and be able to manipulate with objects
Added a clock for time speed changes later on
Add switch for away mode
Add output console and set up state for it
Add enum translation
Add speed rate for clock
Add select options for home location editting, adding new profile
Add user info in rooms

### CODE REVIEW

**Review by jenniferasmar — APPROVED** [review]
Looks really good for now! Only issue is that you can block a window after opening it, not sure if we should allow it

**Review by Karin-kazarian — APPROVED** [review]
Everything is good. 

Small note: This part looks a bit off on my screen if you have time, you can fix 
{15825627-83F2-42AA-A673-212552219B7C}

**Comment by willyyhuang** [comment]
> Everything is good.
> 
> Small note: This part looks a bit off on my screen if you have time, you can fix
> {15825627-83F2-42AA-A673-212552219B7C}

can you let me know which viewport/resolution is this?

**Comment by Karin-kazarian** [comment]
I think it's 1280px × 578px

**Comment by Karin-kazarian** [comment]
> > Everything is good.
> > Small note: This part looks a bit off on my screen if you have time, you can fix
> > {15825627-83F2-42AA-A673-212552219B7C}
> 
> can you let me know which viewport/resolution is this?

I think it's 1280px × 578px

**Comment by willyyhuang** [comment]
@Karin-kazarian @jenniferasmar please re-review

**Pull request merged**
