### PR TITLE
Feature hn modify temperature bcknd

### PR DESCRIPTION
**Pull request by hodansh**
Modify temperature of the house and set date and time.
#15  #21

### CODE REVIEW

**Comment by jenniferasmar** [comment]
The .idea file should be removed before you commit, you can just delete it and push your changes

**Comment by hodansh** [comment]
> The .idea file should be removed before you commit, you can just delete it and push your changes

Ok sure. Thank you.

**Comment by willyyhuang** [comment]
can you add postman screenshots on which url to request and responding data in the pull request

**Comment by hodansh** [comment]
> can you add postman screenshots on which url to request and responding data in the pull request

Yeah sure!

**Review by Karin-kazarian — APPROVED** [review]
Nice job

**Review by jenniferasmar — CHANGES_REQUESTED** [review]
You changed the parameters but not the code. You also need the username as a parameter so you can get the user to modify.

**Review by jenniferasmar — APPROVED** [review]

**Pull request merged**
